### ISSUE TITLE
End position of sigils are not correctly calculated

### ISSUE THREAD

**Issue by msaraiva** [doorgan/sourceror#11]
Hi, thanks for creating this project!

I was playing with the `get_range` function and found an issue when calculating the end position of some sigil calls. Adding this assert to the tests, demonstrates the problem:

```elixir
test "sigils" do
  ...
  
  assert to_range(~S'''
          ~s"""
          foo
          bar
          """
          ''') == %{
            start: [line: 1, column: 1],
            end: [line: 4, column: 4]
          }
end
```

The error:

```
 1) test get_range/1 sigils (SourcerorTest.RangeTest)
     test/range_test.exs:315
     Assertion with == failed
     code:  assert to_range(~S"~s"""
            foo
            bar
            """
            ") == %{start: [line: 1, column: 1], end: [line: 4, column: 4]}
     left:  %{end: [line: 3, column: 2], start: [line: 1, column: 1]}
     right: %{end: [line: 4, column: 4], start: [line: 1, column: 1]}
     stacktrace:
       test/range_test.exs:346: (test)
```

As far as I could see, the issue might be related to not considering the length of the `delimiter` and the extra line when the delimiter is `"""` or `'''`.

**Comment by msaraiva** [comment]
Wow, that was fast! ❤️

Thanks again for this project. I believe it can be a game changer for consistent source manipulation in Elixir.

One question. Is it possible to use sourceror to replace only parts of the code without touching other unrelated parts? For instance, we created a converter for the new [Surface](https://github.com/surface-ui/surface) version that, among other things, updates the syntax of the templates to the new one. Currently, we're using regex to find/replace the content of the old `~H` sigil into the new `~F`, which is sub-optimal so I'm playing with sourceror to see if we could use it for that.

My first attempt was to use `Sourceror.parse_string!/1` + `Sourceror.postwalk/2` to replace the sigil node and then `Sourceror.to_string/1` to get the new content and overwrite the original file. However, `Sourceror.to_string/1` formats the whole content, not only the  parts related to the node I replaced. If the user is using the elixir formatter and the rules are the same, this is probably not a problem, however, if one doesn't use the formatter, we can expect many other unrelated changes in the code.

Do you think there's a way to achieve this in the context of this project? For instance, could `Sourceror.to_string/1` (or maybe a another function) only replace the node's content if is has changed? Or do you think it's better to roll my own solution, maybe based on `get_range` or something similar?

Cheers.

**Comment by doorgan** [comment]
That's something I am exploring now, in the context of fixes for credo issues. What I found useful to do was for the traversal to collect all the places that can be updated, and return a list of "fixes" to be applied at a later stage. The fix is either a `%{range, text}` or `%{range, new_node}` map.

What I'm trying to figure out now is for a reliable way to apply multiple fixes to a same file without the ranges of all but the first fix being "off", and also to take the indentation of the node being replaced into account. But the approach is pretty much the same as the one you described.

I believe `Sourceror.to_string` to be the primitive to convert a node into text(and preserve comments), and that more sophisticated "find and replace" kind of solutions would be built on top of it.

But yes, if we figure it out it would most probably be added to Sourceror, as an additional function, but for now it's a work in progress :)
