### ISSUE TITLE
Test Examples

### ISSUE THREAD

**Issue by andyl** [doorgan/sourceror#20]
With [Rfx](https://github.com/andyl/rfx), to write a good refactoring operation, I find it necessary to test a large number of examples.  The examples are verbose, and tests are long and hard to read.

To streamline things, I have been using a minimalist format to capture examples in a data structure, and a macro that builds and runs data driven tests.  The example data is just a list of 3-element tuples `{title, input-text, expected-text}`.  

Here's the test runner that I use in Rfx:

```elixir
defmacro edit_tst(examples, module) do
  quote do
    Enum.each unquote(examples), fn({testcase, original, expected}) ->
      @testcase testcase
      @original original
      @expected expected |> String.trim()
      test "#{@testcase}" do
        assert @expected == apply(unquote(module), :edit, [@original])
      end
    end
  end
end
```

Click [here](https://github.com/andyl/rfx/blob/master/lib/rfx/util/tst.ex) for the test module that contains the macro.  Click [here](https://github.com/andyl/rfx/blob/master/test/rfx/edit/credo/multi_alias1_test.exs) for a test using example data and the test macro. 

My request for Sourceror:  adopt the list-of-tuples format (or something similar) to capture test examples.  Having a standard way to share examples will IMO make it simpler to report Sourceror bugs and will streamline coordination between Rfx and Sourceror.

**Comment by doorgan** [comment]
Hi Andy!

I like the idea of Sourceror helping to streamline testing of transformations/operations, what I'm unsure about is about this particular case.

For example, Sourceror could provide the `assert_same` macro I use in this repo as a public assertion under a `Sourceror.Test` or `Sourceror.Test.Assertions`, just like Credo does. But when it comes to the 3-tuple, while I really like what you're doing there, I'm unsure about how would that integrate with Sourceror, as its lower level.

In Rfx it makes a lot of sense, because you have a well defined interface for Operations, in the same way that Credo has a well defined interface for the Checks, so having a stardard way to say "This should produce this output from this input" makes a lot of sense, and the tool can automatically call Module.edit for Rfx or Module.run for Credo. But Sourceror doesn't have this, it's basically a set of tools to build something bigger.

There would be ways to tackle this, for example Sourceror could provide some DSL like
```elixir
test_tranforms Module, :function, [global_option: :foo] do
  "test case 1" -> {original, expected}
  "test case 2", [specific_option: :bar] -> {original, expected}
end
```
Where `Module, :function` may as well be a captured function, but this is just a sketch. This is arguably a more complex solution, but it would still let us speak the same langauge when it comes to sharing examples or reporting errors.

Another option would be `Sourceror.Test.cases_for(Module, function, list_of_three_tuples)`, which would be more simple and more in line with your proposal. What do you think?

**Comment by andyl** [comment]
Well firstly, if Sourceror could provide `assert_same` under `Sourceror.Test` or `Sourceror.Test.Assertions`, I would find it very valuable.

Secondly: yeah I understand that Sourceror doesn't have the higher-level interface.  Maybe the best approach is to leave things as-is, and when I come across an issue I'll point you to the failing test in Rfx.

**Comment by doorgan** [comment]
> Well firstly, if Sourceror could provide assert_same under Sourceror.Test or Sourceror.Test.Assertions, I would find it very valuable.

Great, I will expose them soon then!

> Secondly: yeah I understand that Sourceror doesn't have the higher-level interface. Maybe the best approach is to leave things as-is, and when I come across an issue I'll point you to the failing test in Rfx.

FWIW, I think the test helpers are valuable, I believe sooner or later one ends up with a solution similar to yours, because one cares about "I have *this* and I want it to look like *that*" and then there's a bunch of permutations of the pattern, but we need to find a middle ground for the Sourceror APIs so potentially other libraries can benefit from that too.

Personally I don't have a problem looking into Rfx tests whenever you find an issue, so feel free to use whatever makes the most sense for you, as long a it is reproducible I can find a solution :)

**Comment by andyl** [comment]
> Great, I will expose them soon then!

Awesome!

> I believe sooner or later one ends up with a solution similar to yours, ...

In the near term, I'll post issues with failing Rfx tests.  With hands-on experience maybe we will come up with better optimizations, or maybe we'll continue with what we've got.  At the very least, when you look at my tests you'll understand how I'm running the example cases.  :-)

Thanks for your feedback - I'll mark this issue closed, and keep my eyes open for your test assertions.  :+1:
