### ISSUE TITLE
Sourceror.to_string/1 removes all line breaks above comments

### ISSUE THREAD

**Issue by msaraiva** [doorgan/sourceror#28]
Hi there!

I'm not sure if this is directly related to #27 but I also have faced a few issues with comments. For instance, this code:

```elixir
code = ~S"""
# General application configuration
import Config

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason


# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
"""

code |> Sourceror.parse_string!() |> Sourceror.to_string() |> IO.puts
```

Outputs:

```
# General application configuration
import Config
# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason
# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
```

While the formatter:

```elixir
code = ~S"""
# General application configuration
import Config

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason


# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
"""

code |> Code.format_string!() |> IO.puts
```

Outputs:

```
# General application configuration
import Config

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
```

By removing the comments, it works as expected, i.e., it keeps the one like break between each of them.

**Comment by doorgan** [comment]
Hi @msaraiva @novaugust !
Thanks for reporting this, this is indeed a bug.

Sourceror attempts to take care of the comments positions relative to the ast node they are attached to so that the end user doesn't have to, and there's a bug in the algorithm that does this, in the(private) `Sourceror.LinesCorrector` module. The algorithm is quite simple at a high level:
 * If a node has no line number, it's assumed to be in the same line as the previous one.
  * If a node has a line number higher than the one before, it's kept as is.
  * If a node has a line number lower than the one before, it's incremented to be one line higher than it's predecessor
  * If a node has leading comments, it's line number is incremented by the length of the comments list
  * If a node has trailing comments, it's end_of_expression and end line metadata are set to the line of their last child plus the trailing comments list length

Evidently this isn't good enough in the examples that you showcased, so I will look into it and try to come up with a better algorithm.

**Comment by doorgan** [comment]
Seems to be fixed now, so I'm closing this :)
