### ISSUE TITLE
MultiAlias: escaped newline characters

### ISSUE THREAD

**Issue by andyl** [doorgan/sourceror#8]
When I run a 'multi-alias' Sourceror edit script on demo examples, everything is fine.  But when I try to input an Elixir module, the output contains improperly escaped newline characters.  The buggy output look like this:

```elixir
module(DemoMod) do
  @moduledoc """
  Documentation for `DemoMod`.\n"""

  @doc """
  Hello world.\n\n## Examples\n\niex> Wkid.hello()\n:world\n"""

  def hello do
    :world
  end
end
```

To replicate the issue, make a local copy of the RFX repo:
```
> wget https://raw.githubusercontent.com/andyl/rfx/master/test/rfx_setup.sh
> chmod a+rx ./rfx_setup.sh
> ./rfx_setup.sh 566b862
> cd rfx
```

These failing test show the escaped newline characters:
```
> mix test test/rfx/edit/credo/multi_alias1_test.exs:87
> mix test test/rfx/edit/credo/multi_alias1_test.exs:104
```

The module with the Sourceror edit function is at [lib/rfx/edit/credo/multi_alias1.exs](https://github.com/andyl/rfx/blob/master/lib/rfx/edit/credo/multi_alias1.ex).

**Comment by doorgan** [comment]
Thanks for the report!
I looked into it, it's indeed a bug in Sourceror. When you use `Sourceror.parse_string`, it passes the `unscape: false` flag to `Code.string_to_quoted` to preserve escape sequences, for example characters like `\n` will be kept as they are(`\\n`) instead of being converted to a newline character. The problem is that when using `Sourceror.to_string` the `escape: false` flag was not being set and escape sequences were being escaped twice. This is described in the options for [Code.quoted_to_algebra/2](https://hexdocs.pm/elixir/master/Code.html#quoted_to_algebra/2-options) but I just... forgot to use it.

I pushed a fix, let me know if it works :)

The other issue is that in your test you're using `~s`, which doesn't escape characters, and you should expect weirdness because what it returns is not what you would get by reading a file, but an Elixir string with unescaped sequences. You should use `~S` whenever you want to get a string with escaped sequences. With that tiny change the tests for `Rfx` succeed.

**Comment by doorgan** [comment]
Also note that if your edits insert or change a string, it should be done with the `~S` sigil or it should be unescaped. I will look into this too, it's a caveat from the way quoted_to_algebra works and Sourceror should be able to workaround it.

**Comment by andyl** [comment]
Thanks that fixed the double-escape problem.  Thanks for explaining the configuration details that you changed.  Will start to use `~S`.  

In reading your test: interesting approach to format the input code before running thru Sourceror, in order to have a known quantity for before/after comparisons.  I'll start experimenting with that technique.

I have run into another problem (extra parens), and will post that in a separate issue...
