### ISSUE TITLE
MultiAlias: extra parens

### ISSUE THREAD

**Issue by andyl** [doorgan/sourceror#9]
When I run a 'multi-alias' Sourceror edit script on demo examples, everything is fine. But when I try to input an Elixir module, the output contains extra parens around the module name. The buggy output look like this:

```elixir
module(DemoMod) do
  @moduledoc """
  Documentation for `DemoMod`.
  """

  @doc """
  Hello world.

  ## Examples

  iex> Wkid.hello()
  :world
  """

  def hello do
    :world
  end
end
```

To replicate the issue, make a local copy of the RFX repo:

```
> wget https://raw.githubusercontent.com/andyl/rfx/master/test/rfx_setup.sh
> chmod a+rx ./rfx_setup.sh
> ./rfx_setup.sh cdd0b51
> cd rfx
```

This failing test shows the extra parens:

```
> mix test test/rfx/edit/credo/multi_alias1_test.exs:104
```

The module with the Sourceror edit function is at [lib/rfx/edit/credo/multi_alias1.exs](https://github.com/andyl/rfx/blob/dev/lib/rfx/edit/credo/multi_alias1.ex).

**Comment by doorgan** [comment]
This one was a bug on Elixir. The `Code.quoted_to_algebra` runs a normalization step to convert any arbitrary AST into an AST the formatter can understand. The formatter whitelists some calls so that they always omit the parenthesis(like defmodule, def, case, etc). When a call has a do block and is not a whitelisted call, it will check for the presence of `:closing` metadata to decide if the parenthesis should be omitted or not. There is a bug in the normalization step that causes it to always add `:closing` metadata to calls, even if it has a do block.

I sent a PR to Elixir to fix this issue and I pushed a fix to the vendored normalizer in Sourceror. If you're on 1.12 or prior it should work fine now, but for 1.13.0-dev we need to wait for the PR to be merged :)

**Comment by andyl** [comment]
Thanks it works now - awesome.  Great to see the fast Elixir turnaround.
